[package]
name = "xbox_controller"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "xbox_controller"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
defmt = "1.0.1"
embassy-embedded-hal = "0.5.0"
embassy-executor = "0.9.1"
embassy-futures = { version = "0.1.2" }
embassy-time = { version = "0.5.0" }
embedded-storage = "0.3.1"
embedded-storage-async = "0.4.1"
esp-alloc = "0.9.0"
esp-backtrace = { git = "https://github.com/esp-rs/esp-hal", version = "0.18.1", features = [
    "panic-handler",
    "println",
] }
esp-bootloader-esp-idf = { git = "https://github.com/esp-rs/esp-hal", version = "0.4.0" }
esp-hal = { git = "https://github.com/esp-rs/esp-hal", version = "1.0.0", features = [
    "unstable",
] }
esp-println = { git = "https://github.com/esp-rs/esp-hal", version = "0.16.1", features = [
    "defmt-espflash",
] }
esp-radio = { git = "https://github.com/esp-rs/esp-hal", version = "0.17.0", features = [
    "ble",
    "unstable",
] }
esp-rtos = { git = "https://github.com/esp-rs/esp-hal", version = "0.2.0", features = [
    "embassy",
    "esp-radio",
] }
esp-storage = { git = "https://github.com/esp-rs/esp-hal", version = "0.8.1" }
sequential-storage = { version = "7.1.0", features = ["postcard"] }
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
trouble-host = { git = "https://github.com/embassy-rs/trouble", features = [
    "defmt",
    "security",
] }

[features]
default = ["esp32c3"]
esp32c3 = [
    "esp-hal/esp32c3",
    "esp-rtos/esp32c3",
    "esp-backtrace/esp32c3",
    "esp-println/esp32c3",
    "esp-bootloader-esp-idf/esp32c3",
    "esp-radio/esp32c3",
    "esp-alloc/esp32c3",
    "esp-storage/esp32c3",
]
esp32s3 = [
    "esp-hal/esp32s3",
    "esp-rtos/esp32s3",
    "esp-backtrace/esp32s3",
    "esp-println/esp32s3",
    "esp-bootloader-esp-idf/esp32s3",
    "esp-radio/esp32s3",
    "esp-alloc/esp32s3",
    "esp-storage/esp32s3",
]
