[package]
name = "no_std_hello_world"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "no_std_hello_world"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
defmt = "1.0.1"
embassy-executor = "0.9.1"
embedded-hal-bus = "0.3.0"
embedded-sdmmc = "0.9.0"
esp-backtrace = { version = "0.18.1", features = ["defmt", "panic-handler"] }
esp-bootloader-esp-idf = "0.4.0"
esp-hal = { version = "1.0.0", features = ["defmt", "unstable"] }
esp-println = { version = "0.16.1", features = ["defmt-espflash"] }
esp-rtos = { version = "0.2.0", features = ["defmt", "embassy"] }

[features]
default = ["esp32c3"]
esp32c3 = [
    "esp-hal/esp32c3",
    "esp-rtos/esp32c3",
    "esp-backtrace/esp32c3",
    "esp-println/esp32c3",
    "esp-bootloader-esp-idf/esp32c3",
]
