[package]
name = "sd_card_speaker"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sd_card_speaker"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
defmt = "1.0.1"
embassy-executor = "0.9.1"
embassy-sync = { version = "0.7.2", features = ["defmt"] }
embassy-time = { version = "0.5.0", features = ["defmt"] }
esp-backtrace = { version = "0.18.1", features = ["println", "panic-handler"] }
esp-bootloader-esp-idf = "0.4.0"
esp-hal = { version = "1.0.0", features = ["defmt", "unstable"] }
esp-println = { version = "0.16.1", features = ["defmt-espflash"] }
esp-rtos = { version = "0.2.0", features = ["defmt", "embassy"] }
heapless = { version = "0.9.2", features = ["defmt"] }
pure_fat = { version = "1.0.0" }
pure_mbr = { version = "1.0.0" }
pure_wav = { version = "1.0.0" }
spi_sd_card = { git = "https://github.com/ChocolateLoverRaj/spi_sd_card", features = ["defmt", "chrono", "embassy-sync"] }
zerocopy = "0.8.31"

[features]
default = ["esp32c3"]
esp32c3 = [
    "esp-hal/esp32c3",
    "esp-rtos/esp32c3",
    "esp-backtrace/esp32c3",
    "esp-println/esp32c3",
    "esp-bootloader-esp-idf/esp32c3",
]

[patch.crates-io]
crc = { git = "https://github.com/mrhooray/crc-rs" }
