[package]
name = "no_std_hello_world"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "no_std_hello_world"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
crc = "3.4.0"
defmt = "1.0.1"
embassy-embedded-hal = "0.5.0"
embassy-executor = "0.9.1"
embassy-sync = { version = "0.7.2", features = ["defmt"] }
embassy-time = { version = "0.5.0", features = ["defmt"] }
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-hal-bus = "0.3.0"
embedded-timers = "0.4.0"
esp-backtrace = { version = "0.18.1", features = ["panic-handler", "println"] }
esp-bootloader-esp-idf = "0.4.0"
esp-hal = { version = "1.0.0", features = ["defmt", "unstable"] }
esp-println = { version = "0.16.1", features = ["defmt-espflash"] }
esp-rtos = { version = "0.2.0", features = ["defmt", "embassy"] }
heapless = "0.9.2"
pure_fat = { version = "0.1.0", path = "../../pure_fat" }
pure_mbr = { version = "0.1.0", path = "../../pure_mbr" }
spi_sd_card = { version = "0.1.0", path = "../../spi_sd_card", features = ["defmt", "chrono", "embassy-sync"] }
zerocopy = "0.8.31"

[features]
default = ["esp32c3"]
esp32c3 = [
    "esp-hal/esp32c3",
    "esp-rtos/esp32c3",
    "esp-backtrace/esp32c3",
    "esp-println/esp32c3",
    "esp-bootloader-esp-idf/esp32c3",
]
